"""empty message

Revision ID: b26d26967505
Revises: e7b72bd3fd0c
Create Date: 2025-01-24 20:05:58.185418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b26d26967505'
down_revision = 'e7b72bd3fd0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group__finances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_user', sa.Integer(), nullable=False))
        batch_op.drop_constraint('group__finances_create_by_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['id_user'], ['id_user'], ondelete='CASCADE')
        batch_op.drop_column('create_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group__finances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_by', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('group__finances_create_by_fkey', 'users', ['create_by'], ['id_user'], ondelete='CASCADE')
        batch_op.drop_column('id_user')

    # ### end Alembic commands ###
